### ISSUE TITLE
Create Docker tag

### ISSUE THREAD

**Issue by johanhaleby** [whs/kube-slack#1]
Nice work but would you mind tagging the Docker image so that one doesn't have to depend on "latest"?

**Comment by whs** [comment]
I've retroactively tagged v1.0.0, v1.1.0. `latest` will always point to the master branch as we use Docker Hub's automated build.

v1.1.0 have updated Dockerfile from #3.

I'm planning to have v2.0.0 soon that will remove `KIBANA_URL` support per #4. This will break backwards compatibility.
